name: Java Release to Sonatype

on:
 workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: ${{ secrets.MVN_USER }}
          server-password: ${{ secrets.MVN_SECRET }}
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_SECRET}}
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        env:
           gpg_private_key: ${{ secrets.GPG_KEY }}
           passphrase: ${{ secrets.GPG_SECRET }}
      - name: clean
        run: mvn clean
      - name: Create release
        run: mvn release:prepare -Dgpg.passphrase=${{ secrets.GPG_SECRET }}
      - name: Publish to the Maven Central Repository
        run: mvn release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.MVN_USER  }}
          MAVEN_PASSWORD: ${{ secrets.MVN_SECRET }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET }}
