name: Java Release to Sonatype

on:
 workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MVN_USER 
          server-password: MVN_SECRET
          gpg-private-key: MAVEN_GPG_KEY
          gpg-passphrase: MAVEN_GPG_SECRET
      - name: clean
        run: mvn clean
      - name: Create release
        run: mvn release:prepare
      - name: Publish to the Maven Central Repository
        run: mvn release:perform
        env:
          MAVEN_USERNAME: MVN_USER 
          MAVEN_PASSWORD: MVN_SECRET
          MAVEN_GPG_PASSPHRASE: MAVEN_GPG_SECRET
